
package InfoWisata.data;

import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author lenovo
 */
public class FramePelanggan extends javax.swing.JFrame {

    /**
     * Creates new form FramePelanggan
     */
    public FramePelanggan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablePelanggan = new javax.swing.JTable();
        LabelCari = new javax.swing.JLabel();
        EdCari = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        LabelNama = new javax.swing.JLabel();
        LabelKota = new javax.swing.JLabel();
        LabelHarga = new javax.swing.JLabel();
        LabelBuka = new javax.swing.JLabel();
        EdNama = new javax.swing.JTextField();
        EdNamaPelanggan = new javax.swing.JTextField();
        EdAlamat = new javax.swing.JTextField();
        EdUmur = new javax.swing.JTextField();
        EdTelpon = new javax.swing.JTextField();
        BtnSimpan = new javax.swing.JButton();
        BtnUbah = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        BtnBatal = new javax.swing.JButton();
        LabelKet1 = new javax.swing.JLabel();
        CmbIdWisata = new javax.swing.JComboBox<>();
        LabelNama1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA PELANGGAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(jLabel1)
                .addContainerGap(462, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(402, 402, 402))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 40));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        TablePelanggan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TablePelanggan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TablePelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        TablePelanggan.setGridColor(new java.awt.Color(255, 51, 51));
        TablePelanggan.setName("readData"); // NOI18N
        TablePelanggan.setShowVerticalLines(false);
        TablePelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablePelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablePelanggan);
        if (TablePelanggan.getColumnModel().getColumnCount() > 0) {
            TablePelanggan.getColumnModel().getColumn(5).setHeaderValue("Title 6");
        }

        LabelCari.setForeground(new java.awt.Color(255, 255, 255));
        LabelCari.setText("CARI");

        EdCari.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        EdCari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EdCari.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        EdCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EdCariKeyPressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));

        LabelNama.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        LabelNama.setText("ID WISATA");
        LabelNama.setOpaque(true);

        LabelKota.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        LabelKota.setText("NAMA PELANGGAN");
        LabelKota.setOpaque(true);

        LabelHarga.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        LabelHarga.setText("ALAMAT");
        LabelHarga.setOpaque(true);

        LabelBuka.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        LabelBuka.setText("UMUR");
        LabelBuka.setOpaque(true);

        EdNama.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EdNama.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        EdNama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        EdNamaPelanggan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EdNamaPelanggan.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        EdNamaPelanggan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        EdAlamat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EdAlamat.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        EdAlamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        EdUmur.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EdUmur.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        EdUmur.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        EdTelpon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EdTelpon.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        EdTelpon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BtnSimpan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnSimpan.setText("SIMPAN");
        BtnSimpan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });

        BtnUbah.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnUbah.setText("UPDATE");
        BtnUbah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUbahActionPerformed(evt);
            }
        });

        BtnHapus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnHapus.setText("HAPUS");
        BtnHapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });

        BtnBatal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnBatal.setText("BATAL");
        BtnBatal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });

        LabelKet1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        LabelKet1.setText("NO. TELPON");
        LabelKet1.setOpaque(true);

        CmbIdWisata.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "Item 1", "Item 2", "Item 3", "Item 4" }));

        LabelNama1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        LabelNama1.setText("NAMA WISATA");
        LabelNama1.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LabelHarga)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelKota)
                            .addComponent(LabelNama)
                            .addComponent(LabelNama1)
                            .addComponent(LabelKet1)
                            .addComponent(LabelBuka))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EdTelpon, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EdUmur, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EdAlamat, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EdNamaPelanggan, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EdNama, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(CmbIdWisata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BtnUbah, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addComponent(BtnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnHapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnBatal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(36, 36, 36))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNama)
                    .addComponent(CmbIdWisata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdNama, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNama1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelKota)
                    .addComponent(EdNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelHarga)
                    .addComponent(EdAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelBuka)
                    .addComponent(EdUmur, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelKet1)
                    .addComponent(EdTelpon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSimpan)
                    .addComponent(BtnHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnUbah)
                    .addComponent(BtnBatal))
                .addContainerGap(202, Short.MAX_VALUE))
        );

        jButton1.setText("CETAK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(LabelCari)
                        .addGap(18, 18, 18)
                        .addComponent(EdCari, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(46, 46, 46))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCari)
                    .addComponent(EdCari, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 960, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    String koneksi="jdbc:mysql://localhost/info_wisata";
    String user ="root";
    String pass="";
    Connection connection;
    Statement statement;
    private void EdCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EdCariKeyPressed
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("Id Wisata");
        tabel.addColumn("Nama Wisata");
        tabel.addColumn("Nama Pelanggan");
        tabel.addColumn("Alamat");
        tabel.addColumn("Umur");
        tabel.addColumn("No.Telpon");

        try {
            String sql = "select * from pelanggan where id_wisata like '%" + EdCari.getText() + "%'" + "or nama_pelanggan like '%" + EdCari.getText() + "%'";
            ResultSet rs = statement.executeQuery(sql);
            while (rs.next()) {
                tabel.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6)
                });
            }
            TablePelanggan.setModel(tabel);
        }
        catch (Exception DBException)
        {
            System.err.println("Error =" +DBException);
        }
    }//GEN-LAST:event_EdCariKeyPressed

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        try {
            String sql;
            {
                sql= "insert into pelanggan values('";
                sql+= CmbIdWisata.getSelectedItem()+"','";
                sql+= EdNamaPelanggan.getText()+"','";
                sql+= EdAlamat.getText()+"','";
                sql+= EdUmur.getText()+"','";
                sql+= EdTelpon.getText()+"')";

            }
            statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Berhasil meyimpan data","Informasi",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception DBException) {
            JOptionPane.showMessageDialog(this,"Gagal meyimpan data","Error",JOptionPane.ERROR_MESSAGE);
            System.err.println("Error:" +DBException);
        }
        bersih();
        loaddata();
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUbahActionPerformed
        try {
            String sql;
            {
                sql="update pelanggan set nama_pelanggan='";
                sql+= EdNamaPelanggan.getText()+"',alamat='";
                sql+= EdAlamat.getText()+"',umur='";
                sql+= EdUmur.getText()+"',no_telpon='";
                sql+= EdTelpon.getText()+"'";
                sql+= "where id_wisata='" + CmbIdWisata.getSelectedItem()+"'";

            }
            statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(this,"Data berhasil di ubah","Informasi",JOptionPane.INFORMATION_MESSAGE);
        } catch(Exception DBException){
            JOptionPane.showMessageDialog(this, "Gagal mengubah data","Error",JOptionPane.ERROR_MESSAGE);
            System.err.println("Error:" +DBException);
        }
        bersih();
        EdNamaPelanggan.setEditable(true);
        EdNamaPelanggan.requestFocus();
        BtnSimpan.setEnabled(false);
        BtnUbah.setEnabled(false);
        BtnHapus.setEnabled(false);

    }//GEN-LAST:event_BtnUbahActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        try {
            int reply = JOptionPane.showConfirmDialog(this,
                "Apakah anda yakin ingin menghapus data ini?",
                "Konfirmasi",JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (reply==JOptionPane.YES_OPTION){
                String sql="DELETE FROM pelanggan WHERE id_wisata='" + CmbIdWisata.getSelectedItem()+"'";
                statement.executeUpdate(sql);

            }
        }catch(Exception DBException){
            JOptionPane.showMessageDialog(this,"Gagal menghapus data","Error",JOptionPane.ERROR_MESSAGE);
            System.err.println("Error:" +DBException);
        }
        bersih();
        BtnUbah.setEnabled(false);
        BtnHapus.setEnabled(false);
        BtnSimpan.setEnabled(true);
        EdNamaPelanggan.setEditable(true);
        EdNamaPelanggan.requestFocus();
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void TablePelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablePelangganMouseClicked
        CmbIdWisata.setSelectedItem(TablePelanggan.getValueAt(TablePelanggan.getSelectedRow(), 0).toString());
        EdNama.setText(TablePelanggan.getValueAt(TablePelanggan.getSelectedRow(), 1).toString());
        EdNamaPelanggan.setText(TablePelanggan.getValueAt(TablePelanggan.getSelectedRow(), 2).toString());
        EdAlamat.setText(TablePelanggan.getValueAt(TablePelanggan.getSelectedRow(), 3).toString());
        EdUmur.setText(TablePelanggan.getValueAt(TablePelanggan.getSelectedRow(), 4).toString());
        EdTelpon.setText(TablePelanggan.getValueAt(TablePelanggan.getSelectedRow(), 5).toString());
        BtnUbah.setEnabled(true);
        BtnHapus.setEnabled(true);
        EdNama.setEditable(false);
        BtnSimpan.setEnabled(false);
    }//GEN-LAST:event_TablePelangganMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       try {
         Class.forName("com.mysql.jdbc.Driver");
        koneksi="jdbc:mysql://localhost/info_wisata";
        connection=(Connection) DriverManager.getConnection(koneksi,user,pass);
        statement=(Statement) connection.createStatement();
        statement = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
       }
       catch (Exception DBException) {
           JOptionPane.showMessageDialog(this,"Koneksi gagal","Error",JOptionPane.ERROR_MESSAGE);
           System.err.println("Error" +DBException);
       }
       bersih();
       loaddata();
    }//GEN-LAST:event_formWindowOpened

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
       dispose();
    }//GEN-LAST:event_BtnBatalActionPerformed
     
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String jdbc_driver = "com.mysql.jdbc.Driver";
        String url = "jdbc:mysql://localhost/info_wisata";
        String user = "root";
        String pass = "";
        File reportFile = new File(".");
        String dirr = "";
        
        try {
            Class.forName(jdbc_driver);
            Connection conn = (Connection) DriverManager.getConnection(url, user, pass);
            Statement stt = conn.createStatement();
            String sql = "SELECT * FROM pelanggan";
            dirr = reportFile.getCanonicalPath() + "/src/InfoWisata/data/";
            JasperDesign design = JRXmlLoader.load(dirr + "reportPelanggan.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(design);
            ResultSet rs = stt.executeQuery(sql);
            JRResultSetDataSource rsDataSource = new JRResultSetDataSource(rs);
            JasperPrint jp = JasperFillManager.fillReport(jr, new HashMap(), rsDataSource);
            JasperViewer.viewReport(jp);
        } catch (ClassNotFoundException | SQLException | IOException | JRException ex) {
            JOptionPane.showMessageDialog(this,"Gagal mencetak data","Error",JOptionPane.ERROR_MESSAGE);
           
        } 
    }//GEN-LAST:event_jButton1ActionPerformed
      private void loaddata(){
          try {
              CmbIdWisata.removeAllItems();
              String sql="select*from objek_wisata";
              ResultSet rs=statement.executeQuery(sql);
              while(rs.next()){
                  CmbIdWisata.addItem(rs.getString("id_wisata"));
                  
              }
              rs.close();
          }catch(SQLException e){
              System.out.println("terjadi kesalahan");
          }
      }
      
      
      private void bersih(){
        EdNamaPelanggan.setText("");
        EdAlamat.setText("");
        EdUmur.setText("");
        EdTelpon.setText("");
        

        
        try{
            String sql="select objek_wisata.id_wisata, objek_wisata.nama_wisata, pelanggan.nama_pelanggan,pelanggan.alamat,pelanggan.umur,pelanggan.no_telpon"
                    + " from objek_wisata, pelanggan where objek_wisata.id_wisata=pelanggan.id_wisata";
            ResultSet rs=statement.executeQuery(sql);
            final String[] header={"Id Wisata","Nama Wisata","Nama Pelanggan","Alamat","Umur","No. Telpon"};
            rs.last();
            int n=rs.getRow();
            Object[][] data=new Object[n][6];
            int p=0;
            rs.beforeFirst();
            while (rs.next()){
            data [p][0]=rs.getString(1);
            data [p][1]=rs.getString(2);
            data [p][2]=rs.getString(3);
            data [p][3]=rs.getString(4);
            data [p][4]=rs.getString(5);
            data [p][5]=rs.getString(6);

                p++;
                
            }
            TablePelanggan.setModel(new javax.swing.table.DefaultTableModel(data,header));
            TablePelanggan.setAlignmentX(CENTER_ALIGNMENT);
           
            }catch (Exception DBException) {
                System.err.println("Error=" +DBException);
            }
            
      
      
       }
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBatal;
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnSimpan;
    private javax.swing.JButton BtnUbah;
    private javax.swing.JComboBox<String> CmbIdWisata;
    private javax.swing.JTextField EdAlamat;
    private javax.swing.JTextField EdCari;
    private javax.swing.JTextField EdNama;
    private javax.swing.JTextField EdNamaPelanggan;
    private javax.swing.JTextField EdTelpon;
    private javax.swing.JTextField EdUmur;
    private javax.swing.JLabel LabelBuka;
    private javax.swing.JLabel LabelCari;
    private javax.swing.JLabel LabelHarga;
    private javax.swing.JLabel LabelKet1;
    private javax.swing.JLabel LabelKota;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JLabel LabelNama1;
    private javax.swing.JTable TablePelanggan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
